CREATE DATABASE IF NOT EXISTS apipaises;

USE apipaises;

CREATE TABLE IF NOT EXISTS provincias(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
    nombre VARCHAR(150) NOT NULL,
    pais_id BIGINT NOT NULL,
    FOREIGN KEY (pais_id) REFERENCES paises(id)
);
CREATE TABLE IF NOT EXISTS paises(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
    nombre VARCHAR(150) NOT NULL UNIQUE
);
#INSERT PAISES
INSERT INTO paises (nombre) VALUES
    ('Canadá'),
    ('Estados Unidos'),
    ('México'),
    ('Belice'),
    ('Costa Rica'),
    ('El Salvador'),
    ('Guatemala'),
    ('Honduras'),
    ('Nicaragua'),
    ('Panamá'),
    ('Antigua y Barbuda'),
    ('Bahamas'),
    ('Barbados'),
    ('Cuba'),
    ('Dominica'),
    ('Granada'),
    ('Haití'),
    ('Jamaica'),
    ('Puerto Rico'),
    ('República Dominicana'),
    ('San Cristóbal y Nieves'),
    ('Santa Lucía'),
    ('San Vicente y las Granadinas'),
    ('Trinidad y Tobago'),
    ('Argentina'),
    ('Bolivia'),
    ('Brasil'),
    ('Chile'),
    ('Colombia'),
    ('Ecuador'),
    ('Guyana'),
    ('Paraguay'),
    ('Perú'),
    ('Surinam'),
    ('Uruguay');
    
#INSERT PROVINCIAS CANDA
INSERT INTO provincias (nombre, pais_id)
	VALUES
    ('Alberta', 1),
    ('Columbia Británica', 1),
    ('Isla del Príncipe Eduardo', 1),
    ('Manitoba', 1),
    ('Nueva Brunswick', 1),
    ('Nueva Escocia', 1),
    ('Ontario', 1),
    ('Quebec', 1),
    ('Saskatchewan', 1),
    ('Terranova y Labrador', 1);
    
#INSERT PROVINCIAS ESTADOS UNIDOS
INSERT INTO provincias (nombre, pais_id) VALUES
    ('Alabama', 2),
    ('Alaska', 2),
    ('Arizona', 2),
    ('Arkansas', 2),
    ('California', 2),
    ('Colorado', 2),
    ('Connecticut', 2),
    ('Delaware', 2),
    ('Florida', 2),
    ('Georgia', 2),
    ('Hawái', 2),
    ('Idaho', 2),
    ('Illinois', 2),
    ('Indiana', 2),
    ('Iowa', 2),
    ('Kansas', 2),
    ('Kentucky', 2),
    ('Luisiana', 2),
    ('Maine', 2),
    ('Maryland', 2),
    ('Massachusetts', 2),
    ('Míchigan', 2),
    ('Minnesota', 2),
    ('Misisipi', 2),
    ('Misuri', 2),
    ('Montana', 2),
    ('Nebraska', 2),
    ('Nevada', 2),
    ('Nuevo Hampshire', 2),
    ('Nueva Jersey', 2),
    ('Nuevo México', 2),
    ('Nueva York', 2),
    ('Carolina del Norte', 2),
    ('Dakota del Norte', 2),
    ('Ohio', 2),
    ('Oklahoma', 2),
    ('Oregón', 2),
    ('Pensilvania', 2),
    ('Rhode Island', 2),
    ('Carolina del Sur', 2),
    ('Dakota del Sur', 2),
    ('Tennessee', 2),
    ('Texas', 2),
    ('Utah', 2),
    ('Vermont', 2),
    ('Virginia', 2),
    ('Washington', 2),
    ('Virginia Occidental', 2),
    ('Wisconsin', 2),
    ('Wyoming', 2);
    
#INSERT PROVINCIAS MEXICO
INSERT INTO provincias (nombre, pais_id) VALUES
    ('Aguascalientes', 3),
    ('Baja California', 3),
    ('Baja California Sur', 3),
    ('Campeche', 3),
    ('Chiapas', 3),
    ('Chihuahua', 3),
    ('Ciudad de México', 3),
    ('Coahuila', 3),
    ('Colima', 3),
    ('Durango', 3),
    ('Estado de México', 3),
    ('Guanajuato', 3),
    ('Guerrero', 3),
    ('Hidalgo', 3),
    ('Jalisco', 3),
    ('Michoacán', 3),
    ('Morelos', 3),
    ('Nayarit', 3),
    ('Nuevo León', 3),
    ('Oaxaca', 3),
    ('Puebla', 3),
    ('Querétaro', 3),
    ('Quintana Roo', 3),
    ('San Luis Potosí', 3),
    ('Sinaloa', 3),
    ('Sonora', 3),
    ('Tabasco', 3),
    ('Tamaulipas', 3),
    ('Tlaxcala', 3),
    ('Veracruz', 3),
    ('Yucatán', 3),
    ('Zacatecas', 3);

#INSERT PROVINCIAS COSTA RICA
INSERT INTO provincias (nombre, pais_id) VALUES
    ('San José', 5),
    ('Alajuela', 5),
    ('Cartago', 5),
    ('Heredia', 5),
    ('Guanacaste', 5),
    ('Puntarenas', 5),
    ('Limón', 5);

#INSERT PROVINCIAS EL SALVADOR
INSERT INTO provincias (nombre, pais_id) VALUES
    ('Ahuachapán', 6),
    ('Cabañas', 6),
    ('Chalatenango', 6),
    ('Cuscatlán', 6),
    ('La Libertad', 6),
    ('La Paz', 6),
    ('La Unión', 6),
    ('Morazán', 6),
    ('San Miguel', 6),
    ('San Salvador', 6),
    ('San Vicente', 6),
    ('Santa Ana', 6),
    ('Sonsonate', 6),
    ('Usulután', 6);

#INSERT PROVINCIAS GUATEMALA
INSERT INTO provincias (nombre, pais_id) VALUES
    ('Alta Verapaz', 7),
    ('Baja Verapaz', 7),
    ('Chimaltenango', 7),
    ('Chiquimula', 7),
    ('El Progreso', 7),
    ('Escuintla', 7),
    ('Guatemala', 7),
    ('Huehuetenango', 7),
    ('Izabal', 7),
    ('Jalapa', 7),
    ('Jutiapa', 7),
    ('Petén', 7),
    ('Quetzaltenango', 7),
    ('Quiché', 7),
    ('Retalhuleu', 7),
    ('Sacatepéquez', 7),
    ('San Marcos', 7),
    ('Santa Rosa', 7),
    ('Sololá', 7),
    ('Suchitepéquez', 7),
    ('Totonicapán', 7),
    ('Zacapa', 7);

#INSERT PROVINCIAS HONDURAS
INSERT INTO provincias (nombre, pais_id) VALUES
	('Atlántida', 8),
	('Colón', 8),
	('Comayagua', 8),
	('Copán', 8),
	('Cortés', 8),
	('Choluteca', 8),
	('El Paraíso', 8),
	('Francisco Morazán', 8),
	('Gracias a Dios', 8),
	('Intibucá', 8),
	('Islas de la Bahía', 8),
	('La Paz', 8),
	('Lempira', 8),
	('Ocotepeque', 8),
	('Olancho', 8),
	('Santa Bárbara', 8),
	('Valle', 8),
	('Yoro', 8);

#INSERT PROVINCIAS NICARAGUA
INSERT INTO provincias (nombre, pais_id) VALUES
	('Boaco', 9),
	('Carazo', 9),
	('Chinandega', 9),
	('Chontales', 9),
	('Estelí', 9),
	('Granada', 9),
	('Jinotega', 9),
	('León', 9),
	('Madriz', 9),
	('Managua', 9),
	('Masaya', 9),
	('Matagalpa', 9),
	('Nueva Segovia', 9),
	('Río San Juan', 9),
	('Rivas', 9);

#INSERT PROVINCIAS PANAMA
INSERT INTO provincias (nombre, pais_id) VALUES
    ('Bocas del Toro', 10),
    ('Coclé', 10),
    ('Colón', 10),
    ('Chiriquí', 10),
    ('Darién', 10),
    ('Herrera', 10),
    ('Los Santos', 10),
    ('Panamá', 10),
    ('Veraguas', 10);

#INSERT PROVINCIAS BAHAMAS
INSERT INTO provincias (nombre, pais_id) VALUES
	('Acklins', 12),
	('Berry Islands', 12),
	('Bimini', 12),
	('Black Point', 12),
	('Cat Island', 12),
	('Central Abaco', 12),
	('Central Andros', 12),
	('Central Eleuthera', 12),
	('City of Freeport', 12),
	('Crooked Island and Long Cay', 12),
	('East Grand Bahama', 12),
	('Exuma', 12),
	('Grand Cay', 12),
	('Harbour Island', 12),
	('Hope Town', 12),
	('Inagua', 12),
	('Long Island', 12),
	('Mangrove Cay', 12),
	('Mayaguana', 12),
	("Moore's Island", 12),
	('North Abaco', 12),
	('North Andros', 12),
	('North Eleuthera', 12),
	('Ragged Island', 12),
	('Rum Cay', 12),
	('San Salvador', 12),
	('South Abaco', 12),
	('South Andros', 12),
	('South Eleuthera', 12),
	('Spanish Wells', 12),
	('West Grand Bahama', 12);

#INSERT PROVINCIAS PUERTO RICO
INSERT INTO provincias (nombre, pais_id) VALUES
    ('Adjuntas', 19),
    ('Aguada', 19),
    ('Aguadilla', 19),
    ('Aguas Buenas', 19),
    ('Aibonito', 19),
    ('Añasco', 19),
    ('Arecibo', 19),
    ('Arroyo', 19),
    ('Barceloneta', 19),
    ('Barranquitas', 19),
    ('Bayamón', 19),
    ('Cabo Rojo', 19),
    ('Caguas', 19),
    ('Camuy', 19),
    ('Canóvanas', 19),
    ('Carolina', 19),
    ('Cataño', 19),
    ('Cayey', 19),
    ('Ceiba', 19),
    ('Ciales', 19),
    ('Cidra', 19),
    ('Coamo', 19),
    ('Comerío', 19),
    ('Corozal', 19),
    ('Culebra', 19),
    ('Dorado', 19),
    ('Fajardo', 19),
    ('Florida', 19),
    ('Guánica', 19),
    ('Guayama', 19),
    ('Guayanilla', 19),
    ('Guaynabo', 19),
    ('Gurabo', 19),
    ('Hatillo', 19),
    ('Hormigueros', 19),
    ('Humacao', 19),
    ('Isabela', 19),
    ('Jayuya', 19),
    ('Juana Díaz', 19),
    ('Juncos', 19),
    ('Lajas', 19),
    ('Lares', 19),
    ('Las Marías', 19),
    ('Las Piedras', 19),
    ('Loíza', 19),
    ('Luquillo', 19),
    ('Manatí', 19),
    ('Maricao', 19),
    ('Maunabo', 19),
    ('Mayagüez', 19),
    ('Moca', 19),
    ('Morovis', 19),
    ('Naguabo', 19),
    ('Naranjito', 19),
    ('Orocovis', 19),
    ('Patillas', 19),
    ('Peñuelas', 19),
    ('Ponce', 19),
    ('Quebradillas', 19),
    ('Rincón', 19),
    ('Río Grande', 19),
    ('Sabana Grande', 19),
    ('Salinas', 19),
    ('San Germán', 19),
    ('San Juan', 19),
    ('San Lorenzo', 19),
    ('San Sebastián', 19),
    ('Santa Isabel', 19),
    ('Toa Alta', 19),
    ('Toa Baja', 19),
    ('Trujillo Alto', 19),
    ('Utuado', 19),
    ('Vega Alta', 19),
    ('Vega Baja', 19),
    ('Vieques', 19),
    ('Villalba', 19),
    ('Yabucoa', 19),
    ('Yauco', 19);
    
#INSERT PROVINCIAS REPUBLICA DOMINICANA
INSERT INTO provincias (nombre, pais_id) VALUES
	('Azua', 20),
	('Bahoruco', 20),
	('Barahona', 20),
	('Dajabón', 20),
	('Distrito Nacional', 20),
	('Duarte', 20),
	('Elías Piña', 20),
	('El Seibo', 20),
	('Espaillat', 20),
	('Hato Mayor', 20),
	('Hermanas Mirabal', 20),
	('Independencia', 20),
	('La Altagracia', 20),
	('La Romana', 20),
	('La Vega', 20),
	('María Trinidad Sánchez', 20),
	('Monseñor Nouel', 20),
	('Monte Cristi', 20),
	('Monte Plata', 20),
	('Pedernales', 20),
	('Peravia', 20),
	('Puerto Plata', 20),
	('Samaná', 20),
	('Sánchez Ramírez', 20),
	('San Cristóbal', 20),
	('San José de Ocoa', 20),
	('San Juan', 20),
	('San Pedro de Macorís', 20),
	('Santiago', 20),
	('Santiago Rodríguez', 20),
	('Valverde', 20);
    
#INSERT PROVINCIAS ARGENTINA
INSERT INTO provincias (nombre, pais_id) VALUES
	('Buenos Aires', 25),
	('Catamarca', 25),
	('Chaco', 25),
	('Chubut', 25),
	('Córdoba', 25),
	('Corrientes', 25),
	('Entre Ríos', 25),
	('Formosa', 25),
	('Jujuy', 25),
	('La Pampa', 25),
	('La Rioja', 25),
	('Mendoza', 25),
	('Misiones', 25),
	('Neuquén', 25),
	('Río Negro', 25),
	('Salta', 25),
	('San Juan', 25),
	('San Luis', 25),
	('Santa Cruz', 25),
	('Santa Fe', 25),
	('Santiago del Estero', 25),
	('Tierra del Fuego', 25),
	('Tucumán', 25),
	('Ciudad Autónoma de Buenos Aires', 25);

#INSERT PROVINCIAS BOLIVIA
INSERT INTO provincias (nombre, pais_id) VALUES
    ('Beni', 26),
    ('Chuquisaca', 26),
    ('Cochabamba', 26),
    ('La Paz', 26),
    ('Oruro', 26),
    ('Pando', 26),
    ('Potosí', 26),
    ('Santa Cruz', 26),
    ('Tarija', 26);

#INSERT PROVINCIAS BRASIL
INSERT INTO provincias (nombre, pais_id) VALUES
	('Acre', 27),
	('Alagoas', 27),
	('Amapá', 27),
	('Amazonas', 27),
	('Bahía', 27),
	('Ceará', 27),
	('Espírito Santo', 27),
	('Goiás', 27),
	('Maranhão', 27),
	('Mato Grosso', 27),
	('Mato Grosso do Sul', 27),
	('Minas Gerais', 27),
	('Pará', 27),
	('Paraíba', 27),
	('Paraná', 27),
	('Pernambuco', 27),
	('Piauí', 27),
	('Río de Janeiro', 27),
	('Río Grande del Norte', 27),
	('Río Grande del Sur', 27),
	('Rondônia', 27),
	('Roraima', 27),
	('Santa Catarina', 27),
	('São Paulo', 27),
	('Sergipe', 27),
	('Tocantins', 27);

#INSERT PROVINCIAS CHILE
INSERT INTO provincias (nombre, pais_id) VALUES
	('Arica', 28),
	('Parinacota', 28),
	('Iquique', 28),
	('Tamarugal', 28),
	('Antofagasta', 28),
	('El Loa', 28),
	('Tocopilla', 28),
	('Chañaral', 28),
	('Copiapó', 28),
	('Huasco', 28),
	('Choapa', 28),
	('Elqui', 28),
	('Limarí', 28),
	('Valparaíso', 28),
	('Isla de Pascua', 28),
	('Los Andes', 28),
	('Petorca', 28),
	('Quillota', 28),
	('San Antonio', 28),
	('San Felipe de Aconcagua', 28),
	('Cachapoal', 28),
	('Cardenal Caro', 28),
	('Colchagua', 28),
	('Talca', 28),
	('Cauquenes', 28),
	('Curicó', 28),
	('Linares', 28),
	('Concepción', 28),
	('Arauco', 28),
	('Biobío', 28),
	('Ñuble', 28),
	('Cautín', 28),
	('Malleco', 28),
	('Llanquihue', 28),
	('Chiloé', 28),
	('Osorno', 28),
	('Palena', 28),
	('Coyhaique', 28),
	('Aysén', 28),
	('Capitán Prat', 28),
	('General Carrera', 28),
	('Magallanes', 28),
	('Tierra del Fuego', 28),
	('Última Esperanza', 28);

#INSERT PROVINCIAS COLOMBIA
INSERT INTO provincias (nombre, pais_id) VALUES
    ('Amazonas', 29),
    ('Antioquia', 29),
    ('Arauca', 29),
    ('Atlántico', 29),
    ('Bogotá, D.C.', 29),
    ('Bolívar', 29),
    ('Boyacá', 29),
    ('Caldas', 29),
    ('Caquetá', 29),
    ('Casanare', 29),
    ('Cauca', 29),
    ('Cesar', 29),
    ('Chocó', 29),
    ('Córdoba', 29),
    ('Cundinamarca', 29),
    ('Guainía', 29),
    ('Guaviare', 29),
    ('Huila', 29),
    ('La Guajira', 29),
    ('Magdalena', 29),
    ('Meta', 29),
    ('Nariño', 29),
    ('Norte de Santander', 29),
    ('Putumayo', 29),
    ('Quindío', 29),
    ('Risaralda', 29),
    ('San Andrés y Providencia', 29),
    ('Santander', 29),
    ('Sucre', 29),
    ('Tolima', 29),
    ('Valle del Cauca', 29),
    ('Vaupés', 29),
    ('Vichada', 29);
    
#INSERT PROVINCIAS ECUADOR
INSERT INTO provincias (nombre, pais_id) VALUES
    ('Azuay', 30),
    ('Bolívar', 30),
    ('Cañar', 30),
    ('Carchi', 30),
    ('Chimborazo', 30),
    ('Cotopaxi', 30),
    ('El Oro', 30),
    ('Esmeraldas', 30),
    ('Galápagos', 30),
    ('Guayas', 30),
    ('Imbabura', 30),
    ('Loja', 30),
    ('Los Ríos', 30),
    ('Manabí', 30),
    ('Morona Santiago', 30),
    ('Napo', 30),
    ('Orellana', 30),
    ('Pastaza', 30),
    ('Pichincha', 30),
    ('Santa Elena', 30),
    ('Santo Domingo de los Tsáchilas', 30),
    ('Sucumbíos', 30),
    ('Tungurahua', 30),
    ('Zamora-Chinchipe', 30);

#INSERT PROVINCIAS PARAGUAY
INSERT INTO provincias (nombre, pais_id) VALUES
    ('Alto Paraguay', 32),
    ('Alto Paraná', 32),
    ('Amambay', 32),
    ('Boquerón', 32),
    ('Caaguazú', 32),
    ('Caazapá', 32),
    ('Canindeyú', 32),
    ('Central', 32),
    ('Concepción', 32),
    ('Cordillera', 32),
    ('Guairá', 32),
    ('Itapúa', 32),
    ('Misiones', 32),
    ('Ñeembucú', 32),
    ('Paraguarí', 32),
    ('Presidente Hayes', 32),
    ('San Pedro', 32),
    ('Asunción', 32);
    
#INSERT PROVINCIAS PERU
INSERT INTO provincias (nombre, pais_id) VALUES
    ('Amazonas', 33),
    ('Áncash', 33),
    ('Apurímac', 33),
    ('Arequipa', 33),
    ('Ayacucho', 33),
    ('Cajamarca', 33),
    ('Callao', 33),
    ('Cusco', 33),
    ('Huancavelica', 33),
    ('Huánuco', 33),
    ('Ica', 33),
    ('Junín', 33),
    ('La Libertad', 33),
    ('Lambayeque', 33),
    ('Lima (Región Lima)', 33),
    ('Loreto', 33),
    ('Madre de Dios', 33),
    ('Moquegua', 33),
    ('Pasco', 33),
    ('Piura', 33),
    ('Puno', 33),
    ('San Martín', 33),
    ('Tacna', 33),
    ('Tumbes', 33),
    ('Ucayali', 33);
   
#INSERT PROVINCIAS URUGUAY
INSERT INTO provincias (nombre, pais_id) VALUES
    ('Artigas', 35),
    ('Canelones', 35),
    ('Cerro Largo', 35),
    ('Colonia', 35),
    ('Durazno', 35),
    ('Flores', 35),
    ('Florida', 35),
    ('Lavalleja', 35),
    ('Maldonado', 35),
    ('Montevideo', 35),
    ('Paysandú', 35),
    ('Río Negro', 35),
    ('Rivera', 35),
    ('Rocha', 35),
    ('Salto', 35),
    ('San José', 35),
    ('Soriano', 35),
    ('Tacuarembó', 35),
    ('Treinta y Tres', 35);   