version: '3.9'

services:
  java_app:
    container_name: java_app
    image: pee-java-app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - DATABASE_USER=matias
      - DATABASE_PASSWORD=jjkNv4Op
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: 'mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=AnbHd324
      - MYSQL_USER=matias
      - MYSQL_PASSWORD=jjkNv4Op
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
